### ISSUE TITLE
rabbitmq-lvc-plugin is not working with rabbitmq 3.6.6 version

### ISSUE THREAD

**Issue by naveene84** [rabbitmq/rabbitmq-lvc-plugin#14]
Hi,

 I am using rabbitmq 3.6.6 and later versions and trying to get last cache value using lvc plugin (rabbitmq_lvc-0.0.4.ez).

when my consumer tries to declare a new queue and consume lvc value i am getting the following error. The same consumer code is working with 3.6.5. 

[root@EMSDT Rmq_Traffic]# python Consumer_lvc.py
Traceback (most recent call last):
  File "Consumer_lvc.py", line 27, in <module>
    routing_key=bind_key
  File "build/bdist.linux-x86_64/egg/pika/adapters/blocking_connection.py", line 2402, in queue_bind
  File "build/bdist.linux-x86_64/egg/pika/adapters/blocking_connection.py", line 1174, in _flush_output
  File "build/bdist.linux-x86_64/egg/pika/adapters/blocking_connection.py", line 420, in _flush_output
pika.exceptions.ConnectionClosed: (541, 'INTERNAL_ERROR')

**Comment by michaelklishin** [comment]
Please post a script that reproduces the problem. We also need full server logs.

This plugin needs a new build for 3.6.7 and up, I'm not sure about 3.6.6. A new build for 3.6.7+ should be coming later today or tomorrow.

**Comment by naveene84** [comment]
`#!/usr/bin/python2.7
import sys
import pika

queue_name='PresenceQueue1'
exchange_name='RMQKodLvc'
target_ip='XX.XX.XX.141'

credentials = pika.PlainCredentials('rmqAppClient1', 'rmqAppClient1')
parameters = pika.ConnectionParameters(target_ip, 5672, 'RMQBroker1', credentials)
connection = pika.BlockingConnection(parameters)
mdn_list=[91003, 91004, 91005]

def on_message(channel, method, properties,body):
    print "message: {0}".format(body)
    if body=='91005_TF3':
        channel.stop_consuming()

def iterate(list):
    channel = connection.channel()
    channel.exchange_declare(exchange=exchange_name, type="x-lvc", durable=True, auto_delete=False);
    channel.queue_declare(queue=queue_name,  durable=True, auto_delete=True);
    for mdn in list:
        bind_key='prod.'+str(mdn)+'.kodiakptt.com'
        print bind_key
        channel.queue_bind(
            exchange=exchange_name,
            queue=queue_name,
            routing_key=bind_key
        )

    channel.basic_consume(on_message, queue=queue_name, no_ack=True)
    channel.start_consuming()

iterate(mdn_list)
connection.close()
`

**Comment by michaelklishin** [comment]
Thank you!

**Comment by michaelklishin** [comment]
OK, I've just tried this with the tip of stable and a new build of this plugin and it seems to work. I will produce a new LVC release in a bit.

**Comment by michaelklishin** [comment]
A new version [is up on Bintray](https://bintray.com/rabbitmq/community-plugins/rabbitmq_lvc/v3.6.9).

**Comment by naveene84** [comment]
Thanks Michael.  new version is working fine..
